import test from 'node:test';
import assert from 'node:assert/strict';
import {defaultProject,Store,validateProject,makeItem} from '../app/core/store.js';
import {snapshot} from '../app/core/engine.js';
import {hitItem,corners,dbToGain,gainToDb} from '../app/core/util.js';
import {FrameScheduler,AVClock} from '../app/core/clock.js';
import {chooseMime,packet} from '../app/core/output.js';
import {parsePacket,authenticate,validateHello,ffmpegArgs} from '../relay/protocol.mjs';

test('default project has five usable scenes and valid references',()=>{const p=validateProject(defaultProject());assert.equal(p.scenes.length,5);for(const s of p.scenes)for(const i of s.items)assert.ok(p.sources[i.sourceId]);});
test('snapshot isolates source content and item transforms',()=>{const p=defaultProject(),snap=snapshot(p,p.program);const item=p.scenes[0].items[0];item.x=999;p.sources[item.sourceId].config.color='#000000';assert.equal(snap.scene.items[0].x,0);assert.notEqual(snap.sources[item.sourceId].config.color,'#000000');});
test('store undo and redo restore coherent graph state',()=>{const store=new Store();const name=store.project.name;store.mutate('Rename',p=>p.name='Changed');assert.equal(store.project.name,'Changed');store.undo();assert.equal(store.project.name,name);store.redo();assert.equal(store.project.name,'Changed');});
test('stroke transaction coalesces many changes into one undo',()=>{const store=new Store();store.begin('Move');for(let i=0;i<100;i++)store.project.scenes[0].items[0].x=i;store.commit();assert.equal(store.undoStack.length,1);store.undo();assert.equal(store.project.scenes[0].items[0].x,0);});
test('cancel rolls back an unfinished gesture',()=>{const store=new Store();store.begin('Move');store.project.name='bad';store.cancel();assert.equal(store.project.name,'The Creative Signal');assert.equal(store.undoStack.length,0);});
test('invalid source references are rejected',()=>{const p=defaultProject();p.scenes[0].items[0].sourceId='missing';assert.throws(()=>validateProject(p),/reference/);});
test('duplicate scene identity is rejected',()=>{const p=defaultProject();p.scenes[1].id=p.scenes[0].id;assert.throws(()=>validateProject(p),/Duplicate/);});
test('invalid resolution and unknown source types are rejected',()=>{const p=defaultProject();p.settings.width=123;assert.throws(()=>validateProject(p),/dimensions/);const q=defaultProject();Object.values(q.sources)[0].type='remote-script';assert.throws(()=>validateProject(q),/source/);});
test('crop is normalized and numeric filters are clamped',()=>{const p=defaultProject(),i=p.scenes[0].items[0];i.crop.l=.9;i.crop.r=.8;i.filters.brightness=20;i.width=-10;const v=validateProject(p).scenes[0].items[0];assert.ok(v.crop.l+v.crop.r<=.98000001);assert.equal(v.filters.brightness,3);assert.equal(v.width,1);});
test('untrusted external media URLs are discarded',()=>{const p=defaultProject();Object.values(p.sources)[0].config.url='https://invalid.example/track';assert.equal(Object.values(validateProject(p).sources)[0].config.url,undefined);});
test('inverse rotated hit test respects source crop',()=>{const i=makeItem('x',{x:0,y:0,width:100,height:100,rotation:90,crop:{l:.25,t:0,r:0,b:0}});assert.ok(hitItem(i,50,50));assert.ok(!hitItem(i,50,10));assert.equal(corners(i).length,4);});
test('decibels and gain agree',()=>{assert.ok(Math.abs(gainToDb(dbToGain(-12))+12)<1e-9);assert.equal(dbToGain(-60),0);});
test('frame scheduler skips missed deadlines without a catch-up storm',()=>{const s=new FrameScheduler(30);assert.ok(s.due(0));assert.ok(!s.due(.01));assert.ok(s.due(.1));assert.ok(s.late>=1);assert.ok(!s.due(.101));});
test('A/V clock is monotonic across wall-clock queries',()=>{const c=new AVClock({context:null});const first=c.now(c.origin+1000);assert.ok(Math.abs(first-1)<1e-9);assert.equal(c.now(c.origin+500),first);});
test('codec selection probes capabilities rather than assuming MP4',()=>{const Recorder={isTypeSupported:t=>t==='video/webm;codecs=vp8,opus'};assert.equal(chooseMime('auto',Recorder),'video/webm;codecs=vp8,opus');assert.throws(()=>chooseMime('mp4',Recorder),/supported/);});
test('transport packet has exact big-endian sequence and timestamp',()=>{const payload=new Uint8Array([1,2,3,4]);const encoded=packet(7,1200.25,payload);const parsed=parsePacket(Buffer.from(encoded),7,1000);assert.equal(parsed.timecode,1200.25);assert.deepEqual([...parsed.payload],[1,2,3,4]);});
test('transport rejects gaps, regressions, truncation and wrong magic',()=>{const p=Buffer.from(packet(2,25,new Uint8Array([1])));assert.throws(()=>parsePacket(p,1),/Out-of-order/);assert.throws(()=>parsePacket(p,2,30),/regressing/);assert.throws(()=>parsePacket(Buffer.alloc(2),0),/Truncated/);p[0]=0;assert.throws(()=>parsePacket(p,2),/magic/);});
test('tokens require exact equal length and value',()=>{assert.ok(authenticate('secret','secret'));assert.ok(!authenticate('secre','secret'));assert.ok(!authenticate('secrex','secret'));assert.ok(!authenticate(null,'secret'));});
test('relay handshake validates container, version, rate and bitrate',()=>{const hello={type:'hello',version:1,mime:'video/webm;codecs=vp8,opus',fps:30,bitrate:8000000};assert.equal(validateHello(hello),hello);assert.throws(()=>validateHello({...hello,fps:1000}));assert.throws(()=>validateHello({...hello,mime:'application/javascript'}));assert.throws(()=>validateHello({...hello,version:2}));});
test('FFmpeg output uses fixed codecs and an argument vector',()=>{const destination='rtmps://example.invalid/live/secret';const args=ffmpegArgs({fps:30,bitrate:4000000},destination);assert.equal(args.at(-1),destination);assert.ok(args.includes('libx264'));assert.ok(args.includes('aac'));assert.ok(args.includes('pipe:0'));assert.throws(()=>ffmpegArgs({fps:30,bitrate:4000000},'file:///tmp/x'));});
