/** Full loopback transport test: recorded WebM -> SFG1 WebSocket -> FFmpeg ->
 * RTMP listener -> H.264/AAC FLV. Requires npm install, ffmpeg, ffprobe, and a
 * WebM fixture, generated by browser_e2e.py. No external destination is used. */
import {spawn,execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {WebSocket} from 'ws';
import {setTimeout as sleep} from 'node:timers/promises';
import {packet} from '../app/core/output.js';
const root=new URL('../',import.meta.url),art=new URL('artifacts/rtmp/',import.meta.url);
mkdirSync(art,{recursive:true});
const fixture=readFileSync(process.argv[2]||new URL('artifacts/webgpu/recording.webm',import.meta.url));
const destination='rtmp://127.0.0.1:19359/live/signalforge-test';
const out=new URL('loopback.flv',art);const children=[];let socket;
const start=(cmd,args,env)=>{const p=spawn(cmd,args,{cwd:root,env:{...process.env,...env},stdio:['ignore','pipe','pipe']});children.push(p);p.stderr.on('data',d=>process.stderr.write(d));p.on('error',e=>console.error(e.message));return p;};
try {
 const listener=start('ffmpeg',['-y','-hide_banner','-loglevel','warning','-listen','1','-i',destination,'-c','copy',out.pathname]);
 const listenerDone=new Promise(resolve=>listener.on('close',resolve));
 await sleep(500);
 const relay=start(process.execPath,['relay/server.mjs'],{PORT:'8789',SF_RTMP_URL:destination,SF_RELAY_TOKEN:'signalforge-loopback-test-only'});
 let health=false;for(let i=0;i<40;i++){try{health=(await fetch('http://127.0.0.1:8789/api/health')).ok;if(health)break;}catch{}await sleep(100);}
 if(!health)throw new Error('Test relay did not start');
 socket=new WebSocket('ws://127.0.0.1:8789/live','signalforge.v1',{origin:'http://127.0.0.1:8789'});
 let resolveReady,rejectReady,resolveDone,rejectDone,acked=-1;
 const ready=new Promise((r,j)=>{resolveReady=r;rejectReady=j;}),done=new Promise((r,j)=>{resolveDone=r;rejectDone=j;});
 socket.on('message',data=>{const m=JSON.parse(data.toString());if(m.type==='ready')resolveReady(m);if(m.type==='stopped')resolveDone(m);if(m.type==='ack')acked=m.sequence;if(m.type==='error'){rejectReady(new Error(m.message));rejectDone(new Error(m.message));}});
 socket.on('error',e=>{rejectReady(e);rejectDone(e);});
 await new Promise((r,j)=>{socket.once('open',r);socket.once('error',j);});
 socket.send(JSON.stringify({type:'hello',version:1,token:'signalforge-loopback-test-only',mime:'video/webm;codecs=vp8,opus',fps:30,bitrate:2000000}));
 const handshake=await ready;if(handshake.mode!=='rtmp')throw new Error('Relay is not publishing RTMP');
 let seq=0;for(let offset=0;offset<fixture.length;offset+=16000){const payload=fixture.subarray(offset,offset+16000);socket.send(packet(seq,seq*100,payload));seq++;await sleep(100);}
 socket.send(JSON.stringify({type:'end',chunks:seq}));
 const result=await Promise.race([done,sleep(20000).then(()=>{throw new Error('RTMP relay finalization timed out');})]);
 socket.close();await Promise.race([listenerDone,sleep(5000)]);
 const probe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',out.pathname],{encoding:'utf8'}));
 if(!probe.streams.some(s=>s.codec_name==='h264')||!probe.streams.some(s=>s.codec_name==='aac'))throw new Error('Missing H.264/AAC in RTMP receiver output');
 const summary={passed:true,transport:'SFG1 WebSocket -> FFmpeg -> loopback RTMP',bytes:fixture.length,chunks:seq,acked,receiverCodecs:probe.streams.map(s=>s.codec_name),relay:result};
 writeFileSync(new URL('results.json',art),JSON.stringify(summary,null,2));writeFileSync(new URL('probe.json',art),JSON.stringify(probe,null,2));console.log(JSON.stringify(summary,null,2));
} finally {socket?.close();for(const p of children)p.kill('SIGTERM');setTimeout(()=>{for(const p of children)p.kill('SIGKILL');},1500).unref();}
